from __future__ import annotations

import argparse
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Train a lightweight YOLO segmentation model on WormSwin data."
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=Path("data/wormswin_yolo/md/wormswin_md.yaml"),
        help="YOLO dataset YAML generated by prepare_wormswin_yolo.py.",
    )
    parser.add_argument(
        "--model",
        default="yolov8n-seg.pt",
        help="Ultralytics segmentation checkpoint to fine-tune.",
    )
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=4)
    parser.add_argument(
        "--fraction",
        type=float,
        default=1.0,
        help="Fraction of the training dataset to use for quick experiments.",
    )
    parser.add_argument(
        "--device",
        default="0",
        help="Use 0 for the first CUDA GPU, or cpu for CPU-only smoke runs.",
    )
    parser.add_argument("--project", default="runs/wormswin")
    parser.add_argument("--name", default="yolo_seg_md")
    parser.add_argument(
        "--workers",
        type=int,
        default=2,
        help="Data-loader workers. Use 0 if Windows multiprocessing causes trouble.",
    )
    parser.add_argument(
        "--predict-source",
        type=Path,
        help="Optional image folder to run predictions on after training.",
    )
    args = parser.parse_args()

    if not args.data.exists():
        raise SystemExit(f"Missing dataset YAML: {args.data}")
    if args.epochs <= 0:
        raise SystemExit("--epochs must be greater than zero.")
    if args.imgsz <= 0:
        raise SystemExit("--imgsz must be greater than zero.")
    if args.batch <= 0:
        raise SystemExit("--batch must be greater than zero.")
    if not 0 < args.fraction <= 1:
        raise SystemExit("--fraction must be greater than zero and at most one.")

    try:
        from ultralytics import YOLO
    except ImportError as exc:
        raise SystemExit(
            "ultralytics is not installed. Install it with: "
            "python -m pip install ultralytics"
        ) from exc

    model = YOLO(args.model)
    train_result = model.train(
        data=str(args.data),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        project=args.project,
        name=args.name,
        workers=args.workers,
        fraction=args.fraction,
    )
    save_dir = Path(getattr(train_result, "save_dir", Path(args.project) / args.name))
    weights_path = save_dir / "weights" / "best.pt"

    if args.predict_source is not None:
        predictor = YOLO(str(weights_path if weights_path.exists() else args.model))
        predictor.predict(
            source=str(args.predict_source),
            imgsz=args.imgsz,
            device=args.device,
            project=args.project,
            name=f"{args.name}_user_validation_predictions",
            save=True,
            save_txt=True,
        )

    print(f"Training complete: {save_dir}")
    if weights_path.exists():
        print(f"Best weights: {weights_path}")
    metrics = getattr(train_result, "results_dict", None)
    if metrics:
        for key in sorted(metrics):
            value = metrics[key]
            if isinstance(value, (int, float)):
                print(f"{key}: {value:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
